def asciiArt():
	print('Poem Art:')
	print('pride electrician domicile')
	print('whirl pain optoacoustic sophism')
	print('PDP hodgepodge extractor prefer')
	print('abstain calculi headroom')
	print('molybdenum creosote')
	print('anatomist Tenneco')
	print('homesick clink ax vantage')
	print('picosecond immaterial withy')
	print('Burmese tuck')
	print('lime Stuart Kellogg')
	print('circus Cardiff temerity irreconciliable corrode')
	print('fugal oxide Carlo')
	print('Hines wagoneer Clapeyron guidepost')
	print('cool regretted')
	print('sight hidebound handset Berkeley')
	print('rouse quadrature cotangent raindrop')
	print('anatomic mass')
	print('dote cosmopolitan miss hollowware')
	print('Sony mental')
	print('Glenn barfly Bangui Beatrice')
	print('frock persecution then tappet immodest')
	print('northernmost Colette praise')
	print('sou beige chairlady embryonic McCluskey')
	print('neurology Greenberg')
	print('windfall seashore')
	print('Bloomington wigmake wolfish lawmake prosperous')
	print('executor pathogenic incontrovertible pirogue')
	print('oughtnt smuggle asperity mulatto couturier')
	print('synopsis Phelps nodal')
	print('silent convulsive mastodon miracle counterproductive')
	print('park achieve whereas ingather')
	print('macromolecular sanguineous purge knuckle metaphor')
	print('fragmentary Lancashire thoroughbred impend')
	print('UN Belmont')
	print('actress sergeant')
	print('biennial IT&T redshank handicapping godkin')
	print('eddy plankton Planck')
	print('quatrain flop warden bivouac moduli')
	print('sulfanilamide Hrothgar riparian')
	print('downtrend culprit molal')
	print('upside Walt deus still')
	print('Bennington lateral')
	print('Epicurean cryogenic autocorrelate demolish syzygy')
	print('box emblazon teak aloe')
	print('alumina venetian')
	print('toggle en suey botany')
	print('swing formaldehyde tuberous necklace toroid')
	print('snagging Nebuchadnezzar')
	print('crewel thud')
	print('gibe insubordinate fallout Phillip')
	print('jocund crampon thermostat')
	print('squatting gunpowder biharmonic')
	print('tachinid notoriety')
	print('desideratum enthusiast wildflower Mycenaean operon')
	print('bicep exactitude diatomic')
	print('verbal bulbous slivery Howe Pontiac')
	print('Lehigh harangue million Smithfield Jeannie')
	print('flashback tuberculin reportorial')
	print('Goa fond programmable ago')
	print('Sanskrit grammar')
	print('basswood concretion palladium lineal')
	print('Kyle pap')
	print('neonatal showcase standeth')
	print('silversmith Transylvania Lindstrom')
	print('clergy airedale dachshund grandson bet')
	print('scoria Leyden speckle')
	print('grandstand aleph')
	print('handlebar synonymy')
	print('Niamey blather Melissa potlatch category')
	print('Candide friable cabdriver')
	print('approbation aplomb cookbook')
	print('twelve reject computation')
	print('puncture debug witness doberman valedictory')
	print('Munich lodgepole profit sloven foolhardy')
	print('endpoint Regis chromosomal kangaroo zillion')
	print('Lenore sleepwalk thermal')
	print('inconvertible drawn parenthetic upturn depreciable')
