def asciiArt():
	print('Poem Art:')
	print('pride electrician domicile')
	print('whirl pain optoacoustic sophism')
	print('PDP hodgepodge extractor prefer')
	print('abstain calculi headroom')
	print('molybdenum creosote')
	print('anatomist Tenneco')
	print('homesick clink ax vantage')
	print('picosecond immaterial withy')
	print('Burmese tuck')
	print('lime Stuart Kellogg')
	print('circus Cardiff temerity irreconciliable corrode')
	print('fugal oxide Carlo')
	print('Hines wagoneer Clapeyron guidepost')
	print('cool regretted')
	print('sight hidebound handset Berkeley')
	print('rouse quadrature cotangent raindrop')
	print('anatomic mass')
