def asciiArt():
	print('Poem Art:')
	print('pride electrician domicile')
	print('whirl pain optoacoustic sophism')
	print('PDP hodgepodge extractor prefer')
	print('abstain calculi headroom')
	print('molybdenum creosote')
	print('anatomist Tenneco')
	print('homesick clink ax vantage')
	print('picosecond immaterial withy')
	print('Burmese tuck')
	print('lime Stuart Kellogg')
	print('circus Cardiff temerity irreconciliable corrode')
	print('fugal oxide Carlo')
	print('Hines wagoneer Clapeyron guidepost')
	print('cool regretted')
	print('sight hidebound handset Berkeley')
	print('rouse quadrature cotangent raindrop')
	print('anatomic mass')
	print('dote cosmopolitan miss hollowware')
	print('Sony mental')
	print('Glenn barfly Bangui Beatrice')
	print('frock persecution then tappet immodest')
	print('northernmost Colette praise')
	print('sou beige chairlady embryonic McCluskey')
	print('neurology Greenberg')
	print('windfall seashore')
	print('Bloomington wigmake wolfish lawmake prosperous')
	print('executor pathogenic incontrovertible pirogue')
	print('oughtnt smuggle asperity mulatto couturier')
	print('synopsis Phelps nodal')
	print('silent convulsive mastodon miracle counterproductive')
	print('park achieve whereas ingather')
	print('macromolecular sanguineous purge knuckle metaphor')
	print('fragmentary Lancashire thoroughbred impend')
	print('UN Belmont')
	print('actress sergeant')
	print('biennial IT&T redshank handicapping godkin')
	print('eddy plankton Planck')
	print('quatrain flop warden bivouac moduli')
	print('sulfanilamide Hrothgar riparian')
	print('downtrend culprit molal')
	print('upside Walt deus still')
